
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build: ./backend
    volumes:
      - ./backend/logs:/app/logs

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

